### ISSUE TITLE
[Enhancement] Evaluate project boards

### ISSUE THREAD

**Issue by dschier-wtd** [whiletruedoio/tooling#14]
## Description

Organizing tons of issues can be tideous and as a product owner, I want to see new issues and progress at a glance. Evaluating options to present our issues in Kanban style would be great.

## Criteria

- evaluation done
- presented and discussed in this issue
- decision made

**Comment by pdq21** [comment]
How about creating a new project with Githubs native [project boards](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards) for [projects (beta)](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects) and [linking a repository](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/linking-a-repository-to-a-project-board) as PoC?
- Basic [automation for projects](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-automation-for-project-boards) by inserting built-in keywords (To do, In progress, Done) into issues or PR should be provided out-of-the-box.
- Other columns with keywords can be added by [configuring automation for project boards](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/configuring-automation-for-project-boards).
- Maybe boards also provide or will provide a native possibility for issue time tracking and thresholds looked for in [ Enhancement: Stale issues/PRs notifications #4 ](https://github.com/whiletruedoio/tooling/issues/4).

**Comment by daniel-schier** [comment]
@pdq21 I had a very first glance at the project boards, but it was somewhat unintuitive, since the control was label based and one had to add and remove labels or grant access to the board. If you are interested in evaluating this in details, you can grab the story and I can set up a testing repository for the same.

**Comment by pdq21** [comment]
It seems one has to be owner or admin to [create an organization project (beta)](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/creating-a-project#creating-an-organization-project) and [an organization-wide project board](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/creating-a-project-board#creating-an-organization-wide-project-board), meaning the project and the project board have to be created for writers and readers to access them.
There are three [Project board permissions for an organization](https://docs.github.com/en/organizations/managing-access-to-your-organizations-project-boards/project-board-permissions-for-an-organization):
- READ view
- WRITE view, link, interact
- ADMIN above and settings and permission

For starters the Basic Kanban board template with basic automation should suffice.

**Comment by pdq21** [comment]
Update:
- The Automated Kanban template needs to be selected for semi-automation.
- Other templates include bug triage and review.
- Issues from linked repos initially need to be inserted by hand either within the board or the issue.
- Afterwards these issues are somewhat automated.
- Usefulness has to be evaluated.

**Comment by daniel-schier** [comment]
Hi @pdq21,

As I stated, I can prepare this stuff, if you want to take over the evaluation. But you can also create a testing organization on your own.

Do you want to take over this issue? It is quite uncritical for me, since we don't have that many tasks for now.

**Comment by pdq21** [comment]
I already tried yesterday and I can set up a PoC within the org. The experience can come in handy even if there are not too many issues/PR right now.
Since the issues have to be imported manually it is only semi-automatic. Therefore I tried the [GitHub Project Automation+](https://github.com/marketplace/actions/github-project-automation) and got it to work after fiddling with Github secrets.
I also tested the fully-fledged app [ClickUp](https://github.com/marketplace/clickup) with boards and calendars.

**Comment by daniel-schier** [comment]
I had a quick look at ClickUp over the weekend, and it seems really promising. I would love to get a better idea of it. In case you want to take care, I can enable the organization to use it.

**Comment by pdq21** [comment]
Sure. I would suggest to begin with a simple built-in legacy board and advance to ClickUp if need be.
The new boards (beta) offer more sophisticated automation workflows but crashed during testing. They do not seem to be stable right now.
As a starting point an orga admin has to create a legacy board and [assign the relevant permissions to board members](https://docs.github.com/en/organizations/managing-access-to-your-organizations-project-boards/project-board-permissions-for-an-organization).

Furthermore
* Legacy boards require linked repos for the manual import to work properly
* If automatic adding of new issues and PRs to legacy boards is intended, a [repo-token or env-token](https://github.com/marketplace/actions/github-project-automation#personal-access-token) with perms `repo` and `write:org` has to be added for the action to access the repo. See instruction [Personal access token](https://github.com/marketplace/actions/github-project-automation#personal-access-token).
* New boards (beta) do not require linked repos because search over all ressources is enabled by default, e.g. `<name>` or `#`
* Automation with actions seems not to work with new boards (beta) right now but results in error issue or board not found
* ClickUp requires [specific syntax of the naming convention to discover and import issues and PRs](https://docs.clickup.com/en/articles/856285-github), e.g. #{task_id}, CU-{task_id}, {custom_task_id}

**Comment by daniel-schier** [comment]
I will have a look over the weekend :)

**Comment by daniel-schier** [comment]
At least for now, the GitHub project board seems promising. Nevertheless, there is not enough demand to maintain such a board, for now. -> closing, but can be reopened/recreated if needed.
